# Project learnings - captured during implementation
# Processed at cycle-complete into harness updates

corrections:
  - pattern: "Don't use 'Speak to' action buttons on persona cards when multiple personas exist"
    evidence:
      - source: user_correction
        quote: "What happens if 10 personas are active and I don't want to use all of them"
        story: "persona-ux-clarity"
        date: 2026-02-10
    occurrences: 1
    context: "System auto-selects top 3 best-matched personas for questions. Per-persona action buttons are confusing. Use informational status cards instead."

  - pattern: "Persona cards should be informational (status display) not actionable (no buttons per persona)"
    evidence:
      - source: user_correction
        quote: "Yes, much better"
        story: "persona-ux-clarity"
        date: 2026-02-10
    occurrences: 1
    context: "Show active/building status with progress bars. Search bar is the single entry point for both keyword and question modes."

  - pattern: "Run start-story.sh BEFORE attempting any file writes in a story"
    evidence:
      - source: hook_enforcement
        quote: "All edits must go through a story"
        story: "content-type-filter"
        date: 2026-02-10
    occurrences: 1
    context: "Craft write hook checks CURRENT_STORY in .global-state. Must run start-story.sh first to set it."

patterns:
  - pattern: "Persona threshold lowered from 30 to 5 transcripts"
    evidence:
      - source: user_decision
        quote: "Lower to 5 transcripts, and show that to the user"
        story: "persona-ux-clarity"
        date: 2026-02-10
    occurrences: 1

  - pattern: "Show persona building progress (X/5) with 'N more needed' text for channels below threshold"
    evidence:
      - source: user_decision
        quote: "The user should have a clear understanding of why they don't have personas"
        story: "persona-ux-clarity"
        date: 2026-02-10
    occurrences: 1

  - pattern: "Replace generic error messages with specific actionable text"
    evidence:
      - source: user_correction
        quote: "We need a better error state than Something went wrong"
        story: "persona-ux-clarity"
        date: 2026-02-10
    occurrences: 1

errors: []        # Validation failures to prevent

conventions:
  - pattern: "Hint text below search bar explains both modes: keywords for search, questions for personas"
    evidence:
      - source: user_decision
        story: "persona-ux-clarity"
        date: 2026-02-10
    occurrences: 1

automations: []   # Hook/automation opportunities
